name: pet_diary
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  flutter_local_notifications: ^17.0.0
  fl_chart: ^0.68.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_datetime_picker: ^1.5.1
  flutter_colorpicker: ^1.0.3
  search_choices: ^2.2.7
  flutter_typeahead: ^5.2.0
  path: ^1.8.0
  cloud_firestore: ^5.0.1
  multi_select_flutter: ^4.1.3
  flutter_spinkit: ^5.0.0
  pdf: ^3.3.0
  printing: ^5.5.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  flame: ^1.18.0
  pedometer: ^4.0.1
  shared_preferences: ^2.0.8
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  location: ^7.0.0
  apple_maps_flutter: ^1.3.0
  uuid: ^4.4.0
  flutter_image_compress: ^2.3.0
  permission_handler: ^11.3.1
  image_gallery_saver: ^1.7.1
  photo_view: ^0.15.0
  timezone: ^0.9.4
  numberpicker: ^2.1.2
  fake_cloud_firestore: ^3.0.1
  build_runner: ^2.4.11
  mockito: ^5.4.4
  qr_flutter: ^4.1.0
  share_plus: ^9.0.0
  qr_code_scanner: ^ 1.0.1
  carousel_slider: ^4.2.1
  confetti: ^0.7.0
  share: ^2.0.4
  screenshot: ^3.0.0
  barcode_scan2: ^4.2.0
  reorderables: ^ 0.6.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  custom_lint: ^0.6.0
  font_awesome_flutter: ^10.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
    - assets/images/achievements/natural/
    - assets/images/achievements/steps/
    - assets/images/achievements/fantasy/
    - assets/images/events_type_cards/
    - assets/images/dog_avatars/
    - assets/images/dog_backgrounds/
    - assets/images/events_type_cards_no_background/
    - assets/images/others/
    - assets/effects/
    - assets/images/achievements/seasonal/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

  provider: ^5.0.3
