name: pet_diary
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter

  add_2_calendar: ^3.0.1
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.0.0
  fl_chart: ^0.67.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_datetime_picker: ^1.5.1
  flutter_colorpicker: ^1.0.3
  search_choices: ^2.2.7
  flutter_typeahead: ^3.2.1
  path: ^1.8.0
  cloud_firestore: ^4.16.1
  multi_select_flutter: ^4.1.3
  flutter_spinkit: ^5.0.0
  pdf: ^3.3.0
  printing: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.7
  font_awesome_flutter: ^10.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
      - assets/fonts/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

  provider: ^5.0.3
