name: pet_diary
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

  provider: ^5.0.3
