name: pet_diary
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  hive: ^2.0.0
  flutter_riverpod: ^2.4.9
  google_nav_bar: ^5.0.6
  flutter_local_notifications: ^17.0.0
  fl_chart: ^0.68.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  cloud_firestore: ^5.0.1
  flutter_spinkit: ^5.0.0
  pdf: ^3.3.0
  printing: ^5.13.2
  table_calendar: ^3.0.9
  intl: ^0.19.0
  flame: ^1.18.0
  pedometer: ^4.0.1
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  location: ^6.0.2
  uuid: ^4.4.0
  flutter_image_compress: ^2.3.0
  timezone: ^0.9.4
  numberpicker: ^2.1.2
  fake_cloud_firestore: ^3.0.1
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  confetti: ^0.7.0
  screenshot: ^3.0.0
  barcode_scan2: ^4.2.0
  reorderables: ^0.6.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
    - assets/images/achievements/natural/
    - assets/images/achievements/steps/
    - assets/images/achievements/fantasy/
    - assets/images/dog_backgrounds/
    - assets/images/events_type_cards_no_background/
    - assets/images/dog_avatars/
    - assets/images/events_type_cards/
    - assets/images/others/
    - assets/effects/
    - assets/images/achievements/seasonal/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

  provider: ^5.0.3
