name: pet_diary
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  provider: ^5.0.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

  provider: ^5.0.3
