import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:pet_diary/src/components/my_button_widget.dart';
import 'package:pet_diary/src/models/events_icons_module_model.dart';

final modulesProvider = Provider<List<EventsIconsModule>>((ref) {
  final module_1 = EventsIconsModule(
    name: 'L I F E  S T Y L E',
    icons: [
      MyButtonWidget(
        iconData: FontAwesomeIcons.walking,
        label: 'W A L K',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.weight,
        label: 'W E I G H T',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.temperatureHigh,
        label: 'T E M P',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.poop,
        label: 'P O O',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
    ],
    moduleColor: const Color.fromARGB(255, 182, 182, 182),
    padding: const EdgeInsets.all(8.0),
    borderRadius: 15.0,
    fontSize: 13.0,
    fontFamily: 'San Francisco',
    margin: const EdgeInsets.all(8.0),
  );

  final module_2 = EventsIconsModule(
    name: 'M O O D S',
    icons: [
      MyButtonWidget(
        iconData: FontAwesomeIcons.smile,
        label: 'H A P P Y',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.sadCry,
        label: 'S A D',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.tired,
        label: 'T I R E D',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.flushed,
        label: 'F L U',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.chess,
        label: 'S L E A P Y',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.hdr_strong,
        label: 'E N E R G Y',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.check,
        label: 'S T R E S S',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: FontAwesomeIcons.angry,
        label: 'M A D',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
    ],
    moduleColor: const Color.fromARGB(255, 180, 180, 180),
    padding: const EdgeInsets.all(8.0),
    borderRadius: 15.0,
    fontSize: 15.0,
    fontFamily: 'San Francisco',
    margin: const EdgeInsets.all(8.0),
  );

  final module_3 = EventsIconsModule(
    name: 'P I L L S',
    icons: [
      MyButtonWidget(
        iconData: Icons.nordic_walking_sharp,
        label: 'N E W  P I L L S',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
    ],
    moduleColor: const Color.fromARGB(255, 182, 182, 182),
    padding: const EdgeInsets.all(8.0),
    borderRadius: 15.0,
    fontSize: 15.0,
    fontFamily: 'San Francisco',
    margin: const EdgeInsets.all(8.0),
  );

  final module_4 = EventsIconsModule(
    name: 'M Y  N O T E',
    icons: [
      MyButtonWidget(
        iconData: Icons.note,
        label: 'A D D  N O T E',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
    ],
    moduleColor: const Color.fromARGB(255, 180, 180, 180),
    padding: const EdgeInsets.all(8.0),
    borderRadius: 15.0,
    fontSize: 15.0,
    fontFamily: 'San Francisco',
    margin: const EdgeInsets.all(8.0),
  );

  final module_5 = EventsIconsModule(
    name: 'Another Module',
    icons: [
      MyButtonWidget(
        iconData: Icons.nordic_walking_sharp,
        label: 'W A L K',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.edit_calendar,
        label: 'J U R N A L',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.check,
        label: 'R E M I N D E R',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.person,
        label: 'V E T',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.nordic_walking_sharp,
        label: 'W A L K',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.edit_calendar,
        label: 'J U R N A L',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.check,
        label: 'R E M I N D E R',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
      MyButtonWidget(
        iconData: Icons.person,
        label: 'V E T',
        onTap: () {},
        color: const Color.fromARGB(255, 103, 146, 167),
        opacity: 0.6,
        borderRadius: 20.0,
        iconSize: 14.0,
        fontSize: 10.0,
        fontFamily: 'San Francisco',
      ),
    ],
    moduleColor: const Color.fromARGB(255, 180, 180, 180),
    padding: const EdgeInsets.all(8.0),
    borderRadius: 15.0,
    fontSize: 15.0,
    fontFamily: 'San Francisco',
    margin: const EdgeInsets.all(8.0),
  );
  return [module_1, module_2, module_3, module_4, module_5];
});
