// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbXVvewThBqRidl-3G_0_dN88YH-rfgWs',
    appId: '1:405118452244:web:6aedca455cdd7482199d01',
    messagingSenderId: '405118452244',
    projectId: 'pupilapp-3e192',
    authDomain: 'pupilapp-3e192.firebaseapp.com',
    storageBucket: 'pupilapp-3e192.appspot.com',
    measurementId: 'G-E7N7FWFP05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKBfmf-pC1YfOVjopB4rP6gPYiEPu5XF0',
    appId: '1:405118452244:android:3a976ccd0c5c140d199d01',
    messagingSenderId: '405118452244',
    projectId: 'pupilapp-3e192',
    storageBucket: 'pupilapp-3e192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWr0pLAVpl5TraQhkveZ7DJRz8Y-ttP8',
    appId: '1:405118452244:ios:00d3ba8a1f57bdf2199d01',
    messagingSenderId: '405118452244',
    projectId: 'pupilapp-3e192',
    storageBucket: 'pupilapp-3e192.appspot.com',
    iosBundleId: 'com.example.petDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfWr0pLAVpl5TraQhkveZ7DJRz8Y-ttP8',
    appId: '1:405118452244:ios:c14776cd50697f0a199d01',
    messagingSenderId: '405118452244',
    projectId: 'pupilapp-3e192',
    storageBucket: 'pupilapp-3e192.appspot.com',
    iosBundleId: 'com.example.petDiary.RunnerTests',
  );
}
